steps:
- name: gcr.io/cloud-builders/go
  env: ["PROJECT_ROOT=app"]
  args: ["build", "-o", "app"]

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/playground-cloudbuild:$REVISION_ID", "." ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials cluster-1 --zone asia-northeast1-a --project $PROJECT_ID
    kubectl set image deployment/goapp goapp=gcr.io/$PROJECT_ID/playground-cloudbuild:$REVISION_ID


images:
- "gcr.io/$PROJECT_ID/playground-cloudbuild"
