steps:
- name: gcr.io/cloud-builders/go
  env: ["PROJECT_ROOT=app"]
  args: ["build", "-o", "app"]

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/playground-cloudbuild:$REVISION_ID", "." ]


images:
- "gcr.io/$PROJECT_ID/playground-cloudbuild"
