apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: gcr.io/sap20171125/playground-cloudbuild:latest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
